global:
  scrape_interval: 15s  # Set the scrape interval to every 15 seconds

scrape_configs:
  - job_name: 'django-app'
    static_configs:
      - targets: ['172.17.0.2:8000']  # Replace with the actual host and port of your Django app
