name: Django CI/CD

on:
  push:
    branches:
      - main  # Change to your default branch name if different
  pull_request:
    branches:
      - main  # Runs on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the version of Python 3 you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # You can install any dependencies directly here if needed
          # Example: pip install <your-dependencies>
          # If you do not have any dependencies, you can omit this step
          pip install django djangorestframework


      - name: Run Django tests
        run: |
          python manage.py test

      - name: Collect static files
        run: |
          python manage.py collectstatic --noinput

      # Optional: Deploy to your hosting provider, e.g., Heroku, AWS, etc.
      # Uncomment and configure the deployment step if needed
      # - name: Deploy to Heroku
      #   run: |
      #     heroku login --api-key ${{ secrets.HEROKU_API_KEY }}
      #     git push heroku main  # or master depending on your setup

